# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Norwegian Bokmål spellchecker"
nb = "Stavekontroll for norsk bokmål"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Norwegian Bokmål, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
nb = "En stavekontroll for Norwegian Bokmål, laga av medlemmer av Divvun- og Giellateknogruppene ved UiT Norges arktiske universitet"

[macos]
system_pkg_id = "no.divvun.MacDivvun.nb"

[windows]
system_product_code = "{5939C3EA-83E8-4AB7-BE4A-1AE2778750ED}_is1"
legacy_product_codes = [
    { value = "0BEB7B50-5408-48BE-9AED-18992977BD6B", kind = "nsis" },
    { value = "E5B12E99-8DD0-4D7B-9B1D-913CB04728A1", kind = "nsis" }
]

[package.speller]
name = "Norwegian Bokmål"
version = "0.1.1"

[package.grammar]
name = "Norwegian Bokmål"
version = "0.1.0"

[package.tts-textproc]
name = "Norwegian Bokmål"
version = "0.1.0"

[package.hyphenator]
name = "Norwegian Bokmål"
version = "0.1.0"
