template = "https://github.com/giellalt/template-lang-und"
rev_id = 197
template_sha = "bdbeb58949a48fb6da495bd72088ee0ffd09c956"

[replacements]
__REPO__ = "lang-nob"
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
