template = "https://github.com/giellalt/template-lang-und"
rev_id = 198
template_sha = "c528583032290536023c7e6a65d4f1a65dcb0d30"

[replacements]
__REPO__ = "lang-nob"
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
