template = "https://github.com/giellalt/template-lang-und"
rev_id = 36
template_sha = "56da3d5ff7bd29d8ffcc73b853ff7ccc8ef3d406"

[replacements]
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
