template = "https://github.com/giellalt/template-lang-und"
rev_id = 218
template_sha = "f977f8caf5d82030f9681fa655ea0cb16b83f5de"

[replacements]
__REPO__ = "lang-nob"
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
