template = "https://github.com/giellalt/template-lang-und"
rev_id = 48
template_sha = "c312bb110ffaa3c537fb9e5919e473d4cde45ed6"

[replacements]
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
