template = "https://github.com/giellalt/template-lang-und"
rev_id = 15
template_sha = "4dd05bbe948a1e387ae9a7bca33d2467b5359cf7"

[replacements]
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
