template = "https://github.com/giellalt/template-lang-und"
rev_id = 138
template_sha = "47ef5f5258e7a54d9c0b582330dc36eb7b6b1235"

[replacements]
__REPO__ = "lang-nob"
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
