template = "https://github.com/giellalt/template-lang-und"
rev_id = 89
template_sha = "af8541df7c1e45fc9cc76282cc77195dbf8d95b6"

[replacements]
__REPO__ = "lang-nob"
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
