template = "https://github.com/giellalt/template-lang-und"
rev_id = 3
template_sha = "b65dff212e6c7c8bf65765588d14ccdab9baf9dc"

[replacements]
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
