template = "https://github.com/giellalt/template-lang-und"
rev_id = 65
template_sha = "64fd817322b49ba8035465b4ac911accf835c335"

[replacements]
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
