template = "https://github.com/giellalt/template-lang-und"
rev_id = 54
template_sha = "8647ee559596317cbc35543fb22d13bd736f9cc3"

[replacements]
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokm√•l"
__UND__ = "nob"
